// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXyyX40R6UfbCSACI_3SA9Ux4uMapZgrM',
    appId: '1:31207707778:web:65657a9d838e1b4c57909b',
    messagingSenderId: '31207707778',
    projectId: 'remo-login',
    authDomain: 'remo-login.firebaseapp.com',
    storageBucket: 'remo-login.firebasestorage.app',
    measurementId: 'G-CQ6W4F1F9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xtYGRPgdi2lz_5kbbrlNuyRF4Kr19Jg',
    appId: '1:31207707778:android:42636ca158448a3957909b',
    messagingSenderId: '31207707778',
    projectId: 'remo-login',
    storageBucket: 'remo-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmWOBtZXPZSancnJYNXU00BtyYfELTNDw',
    appId: '1:31207707778:ios:ee8b781f8dd91a1e57909b',
    messagingSenderId: '31207707778',
    projectId: 'remo-login',
    storageBucket: 'remo-login.firebasestorage.app',
    iosBundleId: 'com.mycompany.atoz',
  );
}
