// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLc4nd9hTZiYoD4HWgF6A_6CYQYFpOTc0',
    appId: '1:843578977445:web:c1fb0f52caf163b4a4314c',
    messagingSenderId: '843578977445',
    projectId: 'max-taxi-admin-7n82h1',
    authDomain: 'max-taxi-admin-7n82h1.firebaseapp.com',
    storageBucket: 'max-taxi-admin-7n82h1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLc4nd9hTZiYoD4HWgF6A_6CYQYFpOTc0',
    appId: '1:843578977445:android:c1fb0f52caf163b4a4314c',
    messagingSenderId: '843578977445',
    projectId: 'max-taxi-admin-7n82h1',
    storageBucket: 'max-taxi-admin-7n82h1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLc4nd9hTZiYoD4HWgF6A_6CYQYFpOTc0',
    appId: '1:843578977445:ios:c1fb0f52caf163b4a4314c',
    messagingSenderId: '843578977445',
    projectId: 'max-taxi-admin-7n82h1',
    storageBucket: 'max-taxi-admin-7n82h1.appspot.com',
    iosBundleId: 'com.chunguchama.roadygo',
  );
}
